title = "教育云"
name = 1

[[pages]]
name = "堡垒机"

[[pages.entries]]
name = "理工堡垒机"
account = "nblg"
password = "Szlab@1234!"
ip = "10.24.61.210"

[[pages.entries]]
name = "学吧堡垒机"
account = "xbjy"
password = "Szlab@1234!"
ip = "10.24.61.210"

[[pages.entries]]
name = "理工跳板机"
account = "administrator"
password = "Nbjyy@123"
ip = "10.24.61.180"

[[pages]]
name = "服务器"

[[pages.entries]]
name = "课后服务_MQ"
account = "root"
password = "Nbjyy@123"
ip = "10.24.61.71"
port = "22"

[[pages]]
name = "中间件"

[[pages.entries]]
name = "信创_课后服务_OpenGauss"
account = "nbtg_user"
password = "Nbtg@1234"
ip = "198.168.14.42"
port = "15400"

[[pages.entries]]
name = "信创_课后服务_MQ_后台"
account = "admin"
password = "ibdw@123"
ip = "192.168.14.44"
port = "35672"

[[pages.entries]]
name = "信创_课后服务_MQ_应用"
account = "zjsz"
password = "Zjszlab@123456!"
ip = "192.168.14.44"
port = "5678"