title = "平台账号"
name = 2

[[pages]]
name = "人才"

[[pages.entries]]
name = "数据学院"
account = "数据学院"
password = "admin@123"

[[pages.entries]]
name = "计算机专业"
account = "计算机科学与技术"
password = "admin@123"

[[pages.entries]]
name = "朱老师"
account = "05027"
password = "admin@123"

[[pages]]
name = "课后服务_测试"

[[pages.entries]]
name = "宁波市测试学校"
account = "宁波市测试学校"
password = "khfw@123!"

[[pages]]
name = "课后服务"

[[pages.entries]]
name = "市本级"
account = "sbj"
password = "nbkhfw@123!"
